[package]
name = "academic"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Augustin Godinot <agodinot@mpi-sws.org>"]
license = "MIT"
description = "An academic theme for baudelaire, adapted from cstef's paysage theme"
repository = "https://github.com/grodino/grodino.github.io"
keywords = ["baudelaire", "theme", "academic", "landing", "html"]
